-- TO CREATE DATABASE 
CREATE DATABASE USERAUTHENTICATION;

-- TO USE DATABASE 
USE USERAUTHENTICATION;

-- TO CREATE TABLE
CREATE TABLE INFO(
ID INT PRIMARY KEY AUTO_INCREMENT NOT NULL,
Username VARCHAR(250),
Password INT 
);

-- TO DISPLAY THE TABLE
SELECT * FROM INFO;  